apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-world
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-hello-world
        image: registry.hub.docker.com/bharat15/node-helloworld:latest 
        ports:
        - containerPort: 3000

