apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-app
  name: node-hello-world
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32517
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-app
  sessionAffinity: None
  type: LoadBalancer
